- name: Request a DT OAuth access token
  ansible.builtin.uri:
    url: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    method: POST
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body_format: form-urlencoded
    body:
      grant_type: "client_credentials"
      client_id: "{{ extra_vars.dt_oauth_client_id }}"
      client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
      scope: "automation:workflows:write"
      resource: "{{ extra_vars.dt_oauth_account_urn }}"
  register: auth_response_raw
- set_fact:
    dt_oauth_access_token: "{{ auth_response_raw.json.access_token }}"

# - name: Add {{workflow_name}} workflow
# shell: >
#   curl -X 'POST' \
#     '{{ extra_vars.dt_environment_url_gen3 }}/platform/automation/v1/workflows' \
#     -H 'accept: application/json' \
#     -H 'Authorization: Bearer {{ dt_oauth_access_token }}' \
#     -H 'Content-Type: application/json' \
#     -d @/{{path_to_workflow}}
# register: auth_response_raw

- name: Add {{workflow_name}} workflow
  ansible.builtin.uri:
    url: "{{ extra_vars.dt_environment_url_gen3 }}/platform/automation/v1/workflows"
    method: POST
    status_code: [200,201]
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ dt_oauth_access_token }}"
    body: "{{ lookup('ansible.builtin.file', path_to_workflow) }}"
    body_format: json
  register: workflow_post_raw_response
  retries: 10
  delay: 30
  until: workflow_post_raw_response.status != 500

- name: Print variable
  debug: "msg='{{ workflow_post_raw_response }}'"

- set_fact:
    workflow_id: "{{ workflow_post_raw_response.json.id }}"

- set_fact:
    workflow_version: "{{ workflow_post_raw_response.json.version }}"

- name: Print variable
  debug: "msg='{{ workflow_id }}'"
