# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set collections path to prioritize user installation
  ansible.builtin.set_fact:
    ansible_collections_path: "{{ lookup('env', 'HOME') }}/.ansible/collections"

- name: Ensure the easytravel namespace exists
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ easytravel_namespace }}"
    state: present

- name: Create Default Service Account in Namespace
  kubernetes.core.k8s:
    kind: ServiceAccount
    api_version: v1
    name: default
    namespace: "{{ easytravel_namespace }}"
    state: present
  #To make it compatible with older versions of kubernetes.core collection in ext use cases
  ignore_errors: yes
- name: Deploy Easytravel using Helm via curl
  ansible.builtin.shell: |
    helm upgrade --install easytravel "{{ role_path }}/files/helm/easytravel" \
      --namespace "{{ easytravel_namespace }}" \
      --create-namespace \
      --wait \
      --timeout 10m \
      --set ingress.domain="{{ easytravel_domain }}" \
      --set ingress.class="{{ ingress_class }}" \
      --set easytravel.images.tag="{{ easytravel_image_tag }}"
  args:
    executable: /bin/bash

- name: Add dashboard links
  include_tasks: add-dashboard-links.yml
  when: false
