#- name: "Upload Notebook {{ notebook_name }}"
#  ansible.builtin.command: 'curl --location "{{ url_base }}/platform/document/v1/documents"  --header "Authorization: Bearer {{ token }}"  --form "name=\"{{ notebook_name }}\""  --form "type=\"notebook\""  --form "content=@\"{{ notebook_path }}\""'
#  register: post_result

#- name: Get Notebook {{ notebook_name }} Creation Result
#  set_fact:
#    notebook_post_result_json: "{{ post_result.stdout | from_json }}"

#- name: Print return information from the previous task
#  ansible.builtin.debug:
#    var: notebook_post_result_json

#- name: "Share Notebook {{ notebook_name }}"
#  ansible.builtin.uri:
#    url: "{{ url_base }}/platform/document/v1/direct-shares"
#    method: POST
#    status_code: 201
#    headers:
#      Authorization: "Bearer {{ token }}"
#    body_format: json
#    body:
#      documentId: '{{ notebook_post_result_json.id }}'
#      access: read-write
#      recipients:
#      - id: '{{ user_email }}'
#        type: user
#  register: log_response
