configs:
- id: 9f2c728e-fc9a-3d31-bbdf-eb22fd88abc1
  config:
    name: name
    template: 9f2c728e-fc9a-3d31-bbdf-eb22fd88abc1.json
    skip: false
  type:
    settings:
      schema: builtin:appsec.runtime-vulnerability-detection
      scope: environment
