configs:
- id: unguard
  config:
    name: unguard
    template: unguard.json
    skip: false
  type:
    api: application-web

- id: webgoat
  config:
    name: webgoat
    template: webgoat.json
    skip: false
  type:
    api: application-web