configs:
- id: 77abf82c-66b0-3e8a-b6fe-86afae1db7d9
  config:
    name: 77abf82c-66b0-3e8a-b6fe-86afae1db7d9
    template: WebGoat_Dev.json
    skip: false
  type:
    settings:
      schema: builtin:ownership.teams
      scope: environment
- id: 1ae90e28-1ab4-3c5c-8dcf-0aeeb266fd35
  config:
    name: 1ae90e28-1ab4-3c5c-8dcf-0aeeb266fd35
    template: Unguard_Dev.json
    skip: false
  type:
    settings:
      schema: builtin:ownership.teams
      scope: environment

- id: randomUUID
  config:
    name: simplenode
    template: simplenode.json
    skip: false
  type:
    settings:
      schema: builtin:ownership.teams
      scope: environment
