configs:
- id: unguard
  config:
    name: unguard
    parameters:
      unguard_id:
        configId: unguard
        configType: application-web
        property: id
        type: reference
    template: unguard.json
    skip: false
  type:
    settings:
      schema: builtin:rum.web.app-detection
      scope: environment