configs:
- id: 525d4023-de8f-306b-bb0c-3d76ee3b6452
  config:
    name: name
    template: 525d4023-de8f-306b-bb0c-3d76ee3b6452.json
    skip: false
    parameters:
      jira_connection_token:
        type: environment
        name: JIRA_CONNECTION_TOKEN
      jira_user_password:
        type: environment
        name: JIRA_USER_PASSWORD
  type:
    settings:
      schema: app:dynatrace.jira:connection
      scope: environment
      permissions:
        allUsers: write
