configs:
- id: a245cac5-07c9-3ab1-9dce-5ed08f90b543
  config:
    name: name
    template: outbound_connection.json
    skip: false
  type:
    settings:
      schema: builtin:dt-javascript-runtime.allowed-outbound-connections
      scope: environment
