configs:

- id: 5507f5fe-6955-3d21-b8af-da8c97076f42
  config:
    name: unguard
    template: 5507f5fe-6955-3d21-b8af-da8c97076f42.json
    skip: false
  type:
    settings:
      schema: builtin:management-zones
      scope: environment
