---

- include_tasks: enable-audit-logs.yml

- name: Install microk8s
  become: true
  become_user: root
  community.general.snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_release_channel }}"
  register: microk8s

# Install kubectl and helm via snap to not be dependent on microk8s' kube config
- name: Install Kubectl and Helm
  become: true
  become_user: root
  community.general.snap:
    name:
    - kubectl
    - helm
    classic: yes

- name: Install Docker
  become: true
  become_user: root
  community.general.snap:
    name:
    - docker

# Required for Ansible k8s and Docker tasks
- name: Install PIP package
  pip:
    name:
      - kubernetes
      - docker

- name: Persist kube config
  block:
  - ansible.builtin.file:
      path: /home/{{ ace_box_user }}/.kube
      state: directory
      mode: '0700'
  - become: true
    become_user: root
    shell: /snap/bin/microk8s.config > /home/{{ ace_box_user }}/.kube/config
  - ansible.builtin.file:
      path: /home/{{ ace_box_user }}/.kube/config
      owner: "{{ ace_box_user }}"
      group: "{{ ace_box_user }}"
      mode: '0600'
    become: true
    become_user: root
  when: microk8s.changed

- name: Enable Microk8s addons
  block:
  - name: Microk8s - Wait for microk8s to be ready
    become: true
    become_user: root
    shell: /snap/bin/microk8s.status --wait-ready
    register: microk8s_status
    retries: 3
    delay: 30
    until: microk8s_status is not failed
  - name: "Microk8s - Enable addons {{ microk8s_addons }}"
    become: true
    become_user: root
    shell: "/snap/bin/microk8s.enable {{ microk8s_addons }}"
    register: microk8s_addons_enable
    retries: 3
    delay: 60
    until: microk8s_addons_enable is not failed
  - include_tasks:
      file: configure-registry.yml # Includes microk8s restart
  when: microk8s.changed
