# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- block:
    - name: Request a DT OAuth access token
      ansible.builtin.uri:
        url: "{{ dt_oauth_sso_endpoint }}"
        method: POST
        timeout: 120
        status_code: 200
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body_format: form-urlencoded
        body:
          grant_type: "client_credentials"
          client_id: "{{ dt_oauth_client_id }}"
          client_secret: "{{ dt_oauth_client_secret }}"
          scope: "app-engine:apps:install"
          resource: "{{ dt_oauth_account_urn }}"
      register: auth_response_raw
      until: auth_response_raw.json.access_token | length > 0
      retries: 10
      delay: 10

    - set_fact:
        dt_oauth_access_token: "{{ auth_response_raw.json.access_token }}"

- include_role:
    name: dt-platform
    tasks_from: validate-app-version
  vars:
    dt_environment_url_gen3: "{{ extra_vars.dt_environment_url_gen3 }}"
    dt_oauth_sso_endpoint: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    dt_oauth_client_id: "{{ extra_vars.dt_oauth_client_id }}"
    dt_oauth_client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
    dt_oauth_account_urn: "{{ extra_vars.dt_oauth_account_urn }}"

- block:
    - debug:
        msg: "{{ dt_app_version }} of {{ dt_app_id }} is installed in target environment already. Skipping installation."
    - set_fact:
        dt_app_id: "{{ dt_app_id }}"
  when: dt_app_version is defined and dt_app_version is not none

- block:
    - name: "Install app {{ dt_app_id }}"
      ansible.builtin.uri:
        url: "{{ dt_environment_url_gen3.rstrip('/') }}/platform/app-engine/registry/v1/apps"
        method: POST
        status_code: 202
        headers:
          Content-Type: "application/zip"
          Authorization: "Bearer {{ dt_oauth_access_token }}"
        src: "{{ dt_app_artifact_path }}"
      register: post_apps_response_raw
    - set_fact:
        dt_app_id: "{{ post_apps_response_raw.json.id }}"
  when: dt_app_version is not defined or dt_app_version is none
