configs:

  # auto-tag
  - id: autoTag-env
    type: 
      api: auto-tag
    config:
      template: auto-tag-infra.json
      name:
        type: compound
        format: "environment-{{ .demoIdentifier }}"
        references:
          - demoIdentifier
      skip: false
      parameters:
        demoIdentifier: 
          type: environment
          name: DEMO_IDENTIFIER 
        valueFormat: "{ProcessGroup:KubernetesNamespace}"
        dynamicKey: "KUBERNETES_NAMESPACE"
  
  - id: autoTag-app
    type: 
      api: auto-tag
    config:
      template: auto-tag-infra.json
      name:
        type: compound
        format: "app-{{ .demoIdentifier }}"
        references:
          - demoIdentifier
      skip: false
      parameters:
        demoIdentifier: 
          type: environment
          name: DEMO_IDENTIFIER 
        valueFormat: "{ProcessGroup:KubernetesContainerName}"
        dynamicKey: "KUBERNETES_CONTAINER_NAME"

  # request-attribute
  - id: ltn-request-attribute
    type:
      api: request-attributes
    config:
      name:
        type: compound
        format: "LTN-{{ .demoIdentifier }}"
        references:
          - demoIdentifier
      template: request-attribute.json
      parameters:
        delimiter: LTN=
        endDelimiter: ;
        headerName: x-dynatrace-test
        demoIdentifier:
          name: DEMO_IDENTIFIER
          type: environment
      skip: false
  
  - id: tsn-request-attribute
    type:
      api: request-attributes
    config:
      name: 
        type: compound
        format: "TSN-{{ .demoIdentifier }}"
        references:
          - demoIdentifier
      template: request-attribute.json
      parameters:
        delimiter: TSN=
        endDelimiter: ;
        headerName: x-dynatrace-test
        demoIdentifier:
          name: DEMO_IDENTIFIER
          type: environment
      skip: false
  
  - id: lsn-request-attribute
    type:
      api: request-attributes
    config:
      name:  
        type: compound
        format: "LSN-{{ .demoIdentifier }}"
        references:
          - demoIdentifier
      template: request-attribute.json
      parameters:
        delimiter: LSN=
        endDelimiter: ;
        headerName: x-dynatrace-test
        demoIdentifier:
          name: DEMO_IDENTIFIER
          type: environment
      skip: false

